name: "Run Monthly Reminder and Scraper"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # This is the cron expression for once a month at 8 AM GMT+8
jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Run monthly reminder script bot on Telegram and scraper on iSaham
    steps:
      - name: Clone repository.
        uses: actions/checkout@v3
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run python monthly reminder script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python -u monthly_reminder.py
      - name: Run python monthly scraper script
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: python -u scrape.py